[workspace]
exclude = ["fixtures"]
members = ["example", "nested_workspace"]
resolver = "3"

[workspace.dependencies]
anstyle = "1.0"
assert_cmd = "2.0"
anyhow = "1.0"
cargo_metadata = "0.19"
ctor = "0.4"
env_logger = "0.11"
log = "0.4"
regex = "1.11"
serde = "1.0"
serde_json = "1.0"
tempfile = "3.19"
toml = "0.8"
trycmd = "0.15"
walkdir = "2.5"

nested_workspace = { path = "nested_workspace" }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
allow-attributes = { level = "warn", priority = -1 }
missing-errors-doc = "allow"
missing-panics-doc = "allow"
