name: CI

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 3 * * wed"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        environment: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.dylint_drivers/
            ~/.rustup/toolchains/
            target/dylint/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Update/install beta toolchain
        run: rustup toolchain update beta --profile minimal

      - name: Install tools
        run: |
          rustup update
          rustup install nightly
          rustup component add clippy --toolchain nightly
          cargo install cargo-dylint dylint-link || true
          cargo install cargo-msrv               || true

      - name: Build
        run: cargo build --all-targets

      - name: Test
        run: cargo test

  all-checks:
    needs: [test]

    if: ${{ always() }}

    runs-on: ubuntu-latest

    steps:
      - name: Check results
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
